# Generated by Django 4.2.1 on 2023-07-11 22:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
